[package]
name = "vulkan-tutorial-ash"
version = "0.1.0"
authors = ["Adrien Bennadji <adrien.bennadji@live.fr>"]
edition = "2018"
build = "build.rs"

[dependencies]
log = "0.4"
env_logger = "0.6"
ash = "0.27"
winit = "0.18"
cgmath = "0.17.0"
image = "0.21.0"
tobj = "0.1.6"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.6"

[target.'cfg(target_os = "macos")'.dependencies]
metal-rs = "0.6"
cocoa = "0.13"
objc = "0.2.2"
