[package]
name = "vulkan-tutorial-ash"
version = "0.1.0"
authors = ["Adrien Bennadji <adrien.bennadji@live.fr>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
log = "0.4"
env_logger = "0.9"
ash = "0.33"
ash-window = "0.7"
cgmath = "0.18"
image = "0.23"
tobj = "3.2"
ahash = "0.7.6"
winit = { git = "https://github.com/adrien-ben/winit", branch = "android-ndk-0.5" }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { version = "0.5", features = ["logger"] }

# Android manifest
[package.metadata.android]
build_targets = [ "armv7-linux-androideabi", "aarch64-linux-android", "i686-linux-android", "x86_64-linux-android" ]
assets = "assets"

[package.metadata.android.application.activity]
label = "Vulkan tutorial"
orientation = "portrait"
exported = true
