name: Cross-platform build

on: [push]

jobs:
  # Build the project on linux, windows and macos
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Build
        env:
          SKIP_SHADER_COMPILATION: true
        uses: actions-rs/cargo@v1
        with:
          command: build
